apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-audit-test
  annotations:
    codefresh.io/product: octopussamples-octopub-audit
spec:
  project: default
  source:
    repoURL: https://github.com/OctopusSolutionsEngineering/octopub.git
    targetRevision: HEAD
    path: codefresh/helm/octopub-audits/test
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-test
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true