apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-audit-development
  annotations:
    codefresh.io/product: octopussamples-octopub-audit
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/octopub.git
     targetRevision: HEAD
     path: codefresh/helm/octopub-audits/development
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true