apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopussamples-octopub-product-development
  annotations:
    codefresh.io/product: octopussamples-octopub-product
spec:
  project: default
  source:
     repoURL: https://github.com/tweOctopusSolutionsEngineeringrthi/octopub.git
     targetRevision: HEAD
     path: codefresh/helm/octopub-products/development
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-development
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true